function [rawData] = AS_RunExperiment(stimuli, presentationTime,ISI, simseq, sideByside, dotColor,colorNames,windowColor,visualSetup, participantID, windowID, scherm, instructions)
%A function to run an experiment using. This function takes the stimuli and runs an experiment with it
%stimuli - The stimuli matrix generated by AS_CreateStimuli
%stimulusTime - The duration of the stimulus presentation.
%simseq - If the presentation of the stimuli is simultaneous (0) or sequential (1)
%sideBySide - if the stimuli is spatially overlapping (0) or not (1)

ListenChar(2)


ID = participantID;
visualFeatures = AS_FindVisualFeatures(visualSetup);

nrTrials = max(stimuli(:,1));




%Display settings
stimColorN1 = dotColor(1,:);
stimColorN2 = dotColor(2,:);

%Sets the time for the fixation
FixationTime = .5000;

if sideByside == 0
    jitter = 0;
else
    jitter = visualFeatures(3);
end


%Find a position for each of the dots in the two sets. Dots are not allowed
%to overlap
dotPositions = AS_FindDotPositions(stimuli,visualFeatures);

% Find number of dots on each trial and number of dots in each set
nrDotsInTrial = zeros(nrTrials,1);
nrDotsInColor = zeros(nrTrials,2);
for k = 1:nrTrials
    nrDotsInTrial(k) = length(stimuli(stimuli(:,1)==k));
    nrDotsInColor(k,1) = length(stimuli(stimuli(:,1)==k & stimuli(:,8)==1));
    nrDotsInColor(k,2) = length(stimuli(stimuli(:,1)==k & stimuli(:,8)==2));
end

%A random trial list is set up
myTrialList = randsample(1:nrTrials, nrTrials);

if nargin < 13
    [windowID, scherm] = Screen('OpenWindow',0, windowColor);
else
    windowID = windowID;
    scherm = scherm;
end



Screen('FillRect', windowID, windowColor);
Screen('Flip',windowID);

%create a fixation cross that will be used betwee trials
[X,Y] = RectCenter(scherm);
FixCross = [[X-1 Y-40 X+1 Y+40]' [X-40 Y-1 X+40 Y+1]'];


% Make sure keyboard mapping is the same on all supported operating systems
%Apple MacOS/X, MS-Windows and GNU/Linux:
KbName('UnifyKeyNames');

%Init keyboard responses (caps doesn't matter)
color1resp=KbName('f');
color2resp=KbName('k');
[KeyIsDown, endrt, KeyCode]=KbCheck;
Screen('TextSize', windowID, 32);

if nargin < 15
    str = sprintf('You will now see %s and %s dots on the screen. Your task is to decide if there are more %s or %s dots. Press %s if %s is the more numerous color and %s if %s is the more numerous color.',colorNames{1},colorNames{2}, colorNames{1},colorNames{2},KbName(color1resp),colorNames{1},KbName(color2resp),colorNames{2});
    str = WrapString(str);
    respmessage = 'Which color was the more numerous?';
    goodbye_message = 'Thank you for your participation!';
    message = ['Instruction:\n\n' str '\n\n Click the mouse to begin...'];
else
    str = instructions;
    str = WrapString(str);
    respmessage = 'Vilken färg fanns det fler av?';
    goodbye_message = 'Tack för din medverkan! \n\n Kontakta försöksledaren.';
    message = ['Instruktion:\n\n' str '\n\n Klicka på musen för att börja...'];
end



messageStimColor1 = sprintf('%s (f)', colorNames{1});
messageStimColor2 =sprintf('%s (k)',colorNames{2});
DrawFormattedText(windowID, message, 'wrapat', 'center', [0 0 0], 50,[],[],1.63,[], [X-400 Y-300 X+100 Y+300]);
HideCursor(windowID);
%Update the display to show the instruction text:
Screen('Flip', windowID);

%Wait for mouse click:
GetClicks(windowID);


%Clear screen to background color (our 'gray' as set at the beginning):
Screen('FillRect', windowID, windowColor);
Screen('FillRect', windowID, [255,255,255], FixCross);
FixShow = Screen('Flip', windowID);

%Gets the flip interval of the monitor
ifi=Screen('GetFlipInterval', windowID);

%Modifies the presentationtime, isi, and mask time to be even mulitples of
%the monitor flip inteerval
presFrames = round(presentationTime/ifi)-.5;
presentationTime = presFrames*ifi;

ISIFrames = round(ISI/ifi)-.5;
ISI = ISIFrames*ifi;

screenRect =  [0 0 visualFeatures(4) visualFeatures(5)];


%Sets up a rawData matrix that contains information about the stimuli and
%participants response to each trial
rawData = [repmat(ID,nrTrials,1) (1:nrTrials)' zeros(nrTrials, 13) zeros(nrTrials,1)];

%Prepare trials
for j = 1:nrTrials
    thisTrial = sprintf('%s / %s', num2str(j),num2str(nrTrials));
    f = myTrialList(j);
    if f == 1
        startDot = 1;
    else
        startDot = 1 + sum(nrDotsInTrial(1:(f-1)));
    end
    
    endDot = startDot - 1 + nrDotsInTrial(f);
    
    trialDots = dotPositions(:,startDot:endDot);
    
    
    randColor = rand();
    
    if randColor > .5
        C1 = stimColorN1;
        C2 = stimColorN2;
        C1comp = [255 128 0];
        C2comp = [255 0 255];
        color1Orcolor2 = 0; %stimColorN1 is the more numerous
    else
        C1 = stimColorN2;
        C2 = stimColorN1;
        C1comp = [255 0 255];
        C2comp = [255 128 0];
        color1Orcolor2 = 1; %stimColorN2 is the more numerous
    end
    
    %Brings information about the setup of the current trial into the
    %results matrix.
    rawData(j, 3) = stimuli(startDot, 2); %Nr of dots in more numerous set.
    rawData(j, 4) = stimuli(startDot, 3); %Nr of dots in less numerous set.
    rawData(j, 5) = stimuli(startDot, 4); %The ratio of the two sets.
    rawData(j, 6) = stimuli(startDot, 5); %The ratio bin of the stimulus.
    rawData(j, 7) = stimuli(startDot, 6); %If the trial is area controlled (0) or size controlled (1)
    rawData(j, 8) = color1Orcolor2; %If the more numerous set has color 1 (0) or color 2 (1)
    rawData(j, 11)= sum(pi.*stimuli(startDot:startDot+stimuli(startDot, 2)-1,7).^2);%The cummulative area of the larger set
    rawData(j, 12)= sum(pi.*stimuli(startDot+stimuli(startDot,2):startDot+stimuli(startDot,2)+stimuli(startDot, 3)-1,7).^2); %The cummulative area of the smaller set
    rawData(j, 13) = sum(pi.*stimuli(startDot:startDot+stimuli(startDot, 2)-1,7).^2) /stimuli(startDot, 2);  %The average area of the larger set
    rawData(j, 14)= sum(pi.*stimuli(startDot+stimuli(startDot,2):startDot+stimuli(startDot,2)+stimuli(startDot, 3)-1,7).^2) / stimuli(startDot, 3); %The average area of the smaller set
    
    
    
    randPos = rand();
    if randPos <.50
        jitterUse = -jitter;
    else
        jitterUse = jitter;
    end
    
    
    
    %The preparation of the stimuli starts here
    array1 = [trialDots(1,1:nrDotsInColor(f,1))+ jitterUse; trialDots(2,1:nrDotsInColor(f,1)); trialDots(3,1:nrDotsInColor(f,1))+ jitterUse;trialDots(4,1:nrDotsInColor(f,1))];
    array2 = [trialDots(1,nrDotsInColor(f,1)+1:size(trialDots,2))- jitterUse;trialDots(2,nrDotsInColor(f,1)+1:size(trialDots,2)); trialDots(3,nrDotsInColor(f,1)+1:size(trialDots,2))-jitterUse; trialDots(4,nrDotsInColor(f,1)+1:size(trialDots,2))];
    
    if simseq == 0
        Screen('FillOval', windowID, C1,array1);
        Screen('FillOval', windowID, C2,array2);
        StimShow = Screen('Flip',windowID, FixShow + FixationTime);
        FixShowTime = StimShow - FixShow;
        
        
        %Create a messageScreen for the current trial
        Screen('FillRect', windowID, windowColor);
        DrawFormattedText(windowID, respmessage, 'center', Y+250, [0 0 0]);
        DrawFormattedText(windowID,messageStimColor1, X-350, Y+300,stimColorN1);
        DrawFormattedText(windowID,messageStimColor2, X+150, Y+300,stimColorN2);
        DrawFormattedText(windowID,thisTrial, 'center', Y+350,[0 0 0]);
        
        
        respOnset = Screen('Flip',windowID, StimShow + presentationTime);
        StimShowTime = respOnset - StimShow;
        
        responded = 0;
        while responded == 0
            if ( KeyCode(color1resp)==1 || KeyCode(color2resp)==1 )
                ansOnset = Screen('Flip',windowID);
                rawData(j,15) = ansOnset-respOnset;
                
                if KeyCode(color1resp) == 1 && color1Orcolor2 == 0
                    rawData(j,9) = 0;
                    rawData(j,10) = 1;
                elseif KeyCode(color2resp) == 1 && color1Orcolor2 == 1
                    rawData(j,9) = 1;
                    rawData(j,10) = 1;
                elseif KeyCode(color1resp) == 1 && color1Orcolor2 == 1
                    rawData(j,9) = 0;
                    rawData(j,10) = 0;
                else
                    rawData(j,9) = 1;
                    rawData(j,10) = 0;
                end
                
                if j < nrTrials
                    Screen('FillRect', windowID, windowColor);
                    Screen('FillRect', windowID, [255,255,255], FixCross);
                    WaitSecs(.5);
                    FixShow = Screen('Flip', windowID);
                    
                end
                responded = 1;
            end
            [KeyIsDown, endrt, KeyCode]=KbCheck(-1);
            
            WaitSecs(0.001);
        end
        
        
    else
        orderRand = rand();
        
        if orderRand > .5
            Screen('FillOval', windowID, C1,array1);
            FirstStimShow = Screen('Flip',windowID, FixShow + FixationTime);
            rawData(j, 16)= 1; %More numeros is presented first.
            
            
            
            Screen('FillRect', windowID, windowColor, [0 0 visualFeatures(4) visualFeatures(5)]);
            BlankShow = Screen('Flip',windowID, FirstStimShow + presentationTime);
            
            Screen('FillOval', windowID, C2,array2);
            SecondStimShow = Screen('Flip',windowID, BlankShow + ISI);
             
        else
            Screen('FillOval', windowID, C2,array2);
            FirstStimShow = Screen('Flip',windowID, FixShow + FixationTime);
            rawData(j, 16)= 0; %Less numeros is presented first.
            
            
            
            
            Screen('FillRect', windowID, windowColor);
            BlankShow = Screen('Flip',windowID, FirstStimShow + presentationTime);
            
            
            Screen('FillOval', windowID, C1,array1);
            SecondStimShow = Screen('Flip',windowID, BlankShow + ISI);
            
        end
        
        
        
        Screen('FillRect', windowID, windowColor);
        DrawFormattedText(windowID, respmessage, 'center', Y+250, [0 0 0]);
        DrawFormattedText(windowID,messageStimColor1, X-350, Y+300,stimColorN1);
        DrawFormattedText(windowID,messageStimColor2, X+150, Y+300,stimColorN2);
        DrawFormattedText(windowID,thisTrial, 'center', Y+350,[0 0 0]);
        
        
        respOnset = Screen('Flip',windowID, SecondStimShow + presentationTime);
        
        
        responded = 0;
        while responded == 0
            if ( KeyCode(color1resp)==1 || KeyCode(color2resp)==1 )
                ansOnset = Screen('Flip',windowID);
                rawData(j,15) = ansOnset-respOnset;
                
                if KeyCode(color1resp) == 1 && color1Orcolor2 == 0
                    rawData(j,9) = 0;
                    rawData(j,10) = 1;
                elseif KeyCode(color2resp) == 1 && color1Orcolor2 == 1
                    rawData(j,9) = 1;
                    rawData(j,10) = 1;
                elseif KeyCode(color1resp) == 1 && color1Orcolor2 == 1
                    rawData(j,9) = 0;
                    rawData(j,10) = 0;
                else
                    rawData(j,9) = 1;
                    rawData(j,10) = 0;
                end
                
                if j < nrTrials
                    Screen('FillRect', windowID, windowColor);
                    Screen('FillRect', windowID, [255,255,255], FixCross);
                    WaitSecs(.5);
                    FixShow = Screen('Flip', windowID);
                    
                end
                responded = 1;
            end
            [KeyIsDown, endrt, KeyCode]=KbCheck(-1);
            
            WaitSecs(0.001);
        end
        
        
    end
    
    
    
end


Screen('FillRect', windowID, windowColor);


if nargin < 13
    
    DrawFormattedText(windowID, goodbye_message, 'center', 'center', [0 0 0]);
    Screen('Flip',windowID);
    WaitSecs(3.000);
    
    Screen('CloseAll');
    jheapcl()
    ListenChar(0)
end
